languageCode = "en"
languageName = "English"
weight = 1
title = "Asterisk's Den"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "👋 Hi there!"
logo = "./assets/favicon-32x32.png"

[params.author]
name = "Asterisk"
links = [
    { github = "https://github.com/Ast3risk-ops" },
    { mastodon = "https://social.linux.pizza/@asterisk" },
    { discord = "https://discord.com/users/789561823863111742" },
    { telegram = "https://t.me/ast3risk" },
    { element = "https://matrix.to/#/@ast3risk:matrix.org/" },
    { envelope = "mailto:me@asterisk.lol" },
    { ellipsis-vertical = "/socials" }
]
image = "asterisk_ext.png"
headline = "Canadian Linux nerd"
bio = "Canadian Linux nerd"
