colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = false
highlightCurrentMenuArea = true
smartTOC = true

defaultBackgroundImage = "/gm_construct_ballz.jpg"

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = false
showRecentItems = "5"
showMoreLink = true
showMoreLinkDest = "/blog"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "gm_construct_ballz.jpg"

[article]
showDate = true
showComments = true
showViews = false
showLikes = false
showRelatedContent = true
showDateOnlyInArticle = true
showDateUpdated = true
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showZenMode = true
heroStyle = "background"
showSummary = false

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = false
cardView = true

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]
  websiteid = "03a18d89-9829-4a99-af23-833657902d3d"
  domain = "t.asterisk.lol"
  dataDomains = "asterisk.lol"


[buymeacoffee]

[verification]
